线性代数：

标量由只有一个元素的张量表示

In [2]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

可以将向量视为标量值组成的列表

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

可以通过张量的索引来访问任一元素

In [4]:
x[3]

tensor(3)

访问张量的长度

In [5]:
len(x)

4

只有一个轴的张量，形状只有一个元素

In [6]:
x.shape

torch.Size([4])

通过指定两个分量m和n来创建一个形状为m✖n的矩阵

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵，A等于其转置 A = $A^T$

In [10]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)                   # 2个大块，3行4列的小块
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [13]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为 哈达玛积，（数学符号为$\bigodot$）

In [14]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [15]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X,(a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算其元素的和

In [16]:
x = torch.arange(4.0)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [29]:
A = torch.arange(20*2,dtype=torch.float32).reshape(2, 5, 4)
A,A.shape, A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

指定求和汇总张量的轴

In [ ]:
A_sum_axis0 = A.sum(axis=0)                         # 沿着轴0求和，即将两个大块变成一个大块
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [ ]:
A_sum_axis1 = A.sum(axis=1)                         # 沿着轴1求和，即将5行4列的小块变成1行4列的小块
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [25]:
A.sum(axis=[0, 1]), A.sum(axis=[0, 1]).shape           # 沿着轴0和轴1求和，即将两个大块和5行4列的小块都变成一个数

(tensor([180, 190, 200, 210]), torch.Size([4]))

一个与求和相关的量是平均值（mean或average）

In [30]:
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [31]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]                 # 沿着轴0求平均值，即将两个大块变成一个大块

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

计算总和或均值时保持轴数不变

In [35]:
sum_A = A.sum(axis=0, keepdim=True)                      # 沿着轴0求和，并保持轴数不变
sum_A, sum_A.shape

(tensor([[[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 torch.Size([1, 5, 4]))

通过广播将 A 除以 sum_A 

In [33]:
A / sum_A

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

某个轴计算 A 元素的累积求和

In [36]:
A.cumsum(axis=0)                                       # 某个轴计算 A 元素的累积求和

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

点积是相同位置的按元素乘积的和

In [37]:
y = torch.ones(4,dtype=torch.float32)
x,y, torch.dot(x,y)                                       # 点积是相同位置的按元素乘积的和

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [39]:
torch.sum(x * y)

tensor(6.)

矩阵向量积 Ax

In [41]:
A.shape,x.shape,torch.mv(A[0], x)                                       # 矩阵向量积 Ax

(torch.Size([2, 5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法AB看作是简单执行m次矩阵-向量积，并将结果拼接在一起

In [43]:
B = torch.ones(4,3)
torch.mm(A[0],B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根：

$$||\mathbf{x}||_2 = \sqrt{\sum_{i=1}^{n} x_i^2}$$

In [44]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)                                       # L2范数是向量元素平方和的平方根：

tensor(5.)

L1范数，它表示向量元素的绝对值之和

$$||\mathbf{x}||_1 = \sum_{i=1}^{n} |x_i|$$

In [46]:
torch.abs(u).sum()                                       # L1范数，它表示向量元素的绝对值之和

tensor(7.)

矩阵的弗罗贝尼乌斯范数是矩阵元素的平方和的平方根：

$$||\mathbf{X}||_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$$

In [47]:
torch.norm(torch.ones((4,9)))                               # 矩阵的Frobenius范数是矩阵元素平方和的平方根

tensor(6.)